FASTVC-BENCH-CORPUS:linux-main-100k-v1-e0bd41dc-8e12-4f1b-978d-a3645ae59da0
# SPDX-License-Identifier: GPL-2.0
AM_CPPFLAGS = -I$(top_srcdir)/libsrc -DUSBIDS_FILE='"@USBIDS_DIR@/usb.ids"'
/* bench 28918.4.0 4b557c06ee43 */
/* bench 28918.4.1 d3e764cd14c3 */
/* bench 28918.4.2 f36cd56b4538 */
/* bench 28918.4.3 29fc03121224 */
/* bench 28918.4.4 5b00da51e38a */
/* bench 28918.4.5 b956da920102 */
/* bench 28918.4.6 b3ae919caff0 */
/* bench 28918.4.7 7b668fe1793c */
LDADD       = $(top_builddir)/libsrc/libusbip.la

sbin_PROGRAMS := usbip usbipd

usbip_SOURCES := usbip.h utils.h usbip.c utils.c usbip_network.c \
		 usbip_attach.c usbip_detach.c usbip_list.c \
		 usbip_bind.c usbip_unbind.c usbip_port.c

usbipd_SOURCES := usbip_network.h usbipd.c usbip_network.c
