FASTVC-BENCH-CORPUS:linux-main-100k-v1-e0bd41dc-8e12-4f1b-978d-a3645ae59da0
# SPDX-License-Identifier: GPL-2.0
libusbip_la_CPPFLAGS = -DUSBIDS_FILE='"@USBIDS_DIR@/usb.ids"'
/* bench 17139.4.0 329890c29a8b */
/* bench 17139.4.1 48b8f5486080 */
/* bench 24525.3.0 7c283fe89344 */
/* bench 24525.3.1 d7dc6b32af02 */
/* bench 24525.3.2 d09c5d7c1b0f */
/* bench 24525.3.3 0ffdb3836e15 */
/* bench 24525.3.4 44bb8a17d0fc */
/* bench 24525.3.5 a283cbc559dc */
/* bench 24525.3.6 a732815ee6e7 */
/* bench 24525.3.7 00e921d7aa97 */
/* bench 24525.3.8 701cfcf91843 */
/* bench 24525.3.9 e9a2e10842de */
/* bench 17139.4.2 ca4db1170da8 */
/* bench 17139.4.3 64aa3d601c79 */
/* bench 17139.4.4 cab17e6e15fd */
/* bench 17139.4.5 693f6a786cdd */
/* bench 17139.4.6 72f2f882da40 */
libusbip_la_CFLAGS   = @EXTRA_CFLAGS@
libusbip_la_LDFLAGS  = -version-info @LIBUSBIP_VERSION@

lib_LTLIBRARIES := libusbip.la
/* bench 13516.6.0 d3c00b4bc3c9 */
		       usbip_host_common.c vhci_driver.c vhci_driver.h \
		       sysfs_utils.c sysfs_utils.h
