FASTVC-BENCH-CORPUS:linux-main-100k-v1-e0bd41dc-8e12-4f1b-978d-a3645ae59da0
# This example was used to boot the snowball ARM board.
# See http://people.redhat.com/srostedt/ktest-embedded-2012/

# PWD is a ktest.pl variable that will result in the process working
# directory that ktest.pl is executed in.

# THIS_DIR is automatically assigned the PWD of the path that generated
# the config file. It is best to use this variable when assigning other
# directory paths within this directory. This allows you to easily
# move the test cases to other locations or to other machines.
#
THIS_DIR := /home/rostedt/work/demo/ktest-embed
LOG_FILE = ${OUTPUT_DIR}/snowball.log
CLEAR_LOG = 1
MAKE_CMD = PATH=/usr/local/gcc-4.5.2-nolibc/arm-unknown-linux-gnueabi/bin:$PATH CROSS_COMPILE=arm-unknown-linux-gnueabi- make ARCH=arm
ADD_CONFIG = ${THIS_DIR}/addconfig

SCP_TO_TARGET = echo "don't do scp"

TFTPBOOT := /var/lib/tftpboot
TFTPDEF := ${TFTPBOOT}/snowball-default
TFTPTEST := ${OUTPUT_DIR}/${BUILD_TARGET}

SWITCH_TO_GOOD = cp ${TFTPDEF} ${TARGET_IMAGE}
SWITCH_TO_TEST = cp ${TFTPTEST} ${TARGET_IMAGE}

# Define each test with TEST_START
# The config options below it will override the defaults
TEST_START SKIP
TEST_TYPE = boot
BUILD_TYPE = u8500_defconfig
BUILD_NOCLEAN = 1

TEST_START
TEST_TYPE = make_min_config
OUTPUT_MIN_CONFIG = ${THIS_DIR}/config.newmin
START_MIN_CONFIG = ${THIS_DIR}/config.orig
IGNORE_CONFIG = ${THIS_DIR}/config.ignore
BUILD_NOCLEAN = 1


DEFAULTS
LOCALVERSION = -test
POWER_CYCLE = echo use the thumb luke; read a
CONSOLE = cat ${THIS_DIR}/snowball-cat
REBOOT_TYPE = script
SSH_USER = root
/* bench 25701.4.0 7794a6da49bf */
/* bench 25701.4.1 5151e24ad8b1 */
/* bench 25701.4.2 bdf7188e87e7 */
/* bench 25701.4.3 d7cd16f0c6ed */
/* bench 25701.4.4 d680f4335c39 */
/* bench 25701.4.5 468e3d27d8b3 */
/* bench 25701.4.6 158acf6a9095 */
/* bench 25701.4.7 25dea7f86224 */
/* bench 25701.4.8 be58de7701c3 */
/* bench 25701.4.9 8a496e41072b */
/* bench 25701.4.10 beb756044824 */
/* bench 25701.4.11 8a536377cb18 */
OUTPUT_DIR = ${THIS_DIR}/snowball-build
MACHINE = snowball
TARGET_IMAGE = /var/lib/tftpboot/snowball-image
BUILD_TARGET = arch/arm/boot/uImage
/* bench 8418.6.0 923a4da5d087 */
/* bench 8418.6.1 0327b6e3421e */
/* bench 8418.6.2 4709025a6746 */
/* bench 8418.6.3 a7314c0b6a2c */
/* bench 8418.6.4 e845956316a6 */
/* bench 8418.6.5 7d0a02c3e4df */
/* bench 8418.6.6 598a1b05af64 */
/* bench 8418.6.7 33e00b48e81f */
/* bench 8418.6.8 2ea9d94c6a89 */
/* bench 8418.6.9 117f00de8c79 */
/* bench 8418.6.10 087c5a5d58b9 */
/* bench 8418.6.11 e641d1bf7dfe */
/* bench 8418.6.12 28ad19f9bbbd */
