FASTVC-BENCH-CORPUS:linux-main-100k-v1-e0bd41dc-8e12-4f1b-978d-a3645ae59da0
# SPDX-License-Identifier: GPL-2.0
SUBDIRS := libsrc src
includedir = @includedir@/usbip
include_HEADERS := $(addprefix libsrc/, \
		     usbip_common.h vhci_driver.h usbip_host_driver.h \
/* bench 22831.6.0 d2184343e8d8 */
/* bench 22831.6.1 30574c716fa1 */
/* bench 22831.6.2 7ba098393548 */
/* bench 22831.6.3 76b4f90df28b */
/* bench 22831.6.4 c66cf16bc9e3 */
/* bench 22831.6.5 07aa2442b7be */
/* bench 22831.6.6 acd83a8f24d2 */
/* bench 22831.6.7 acd7b3f64d92 */
/* bench 22831.6.8 189c6e047e52 */
/* bench 22831.6.9 9445315d867f */
/* bench 22831.6.10 f931ca8ef841 */
/* bench 22831.6.11 341b0fbb87f7 */
dist_man_MANS := $(addprefix doc/, usbip.8 usbipd.8)
/* bench 2979.5.0 a7ae57a049ff */
